name: SPARQL Monitor Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Try Poetry first
        if [ -f pyproject.toml ]; then
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
        # Fallback to requirements.txt
        elif [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No dependencies file found"
          exit 1
        fi
        
    - name: Run SPARQL monitor
      run: |
        if [ -f pyproject.toml ]; then
          poetry run python -m main
        else
          python -m main
        fi
        
    - name: Upload monitoring results
      uses: actions/upload-artifact@v3
      with:
        name: monitor-results
        path: monitor_results/
        
    - name: Create Pull Request with results
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Add monitoring results
        title: 'Monitoring Results Update'
        body: |
          New monitoring results have been generated.
          - Auto-generated by GitHub Actions
        branch: monitoring-results
        base: main